export type Health="healthy"|"watch"|"attention"|"critical";
export type AnalysisAlert={code:string;health:Health;title:string;observation:string;economicInterpretation:string;simpleExplanation:string;risk:string;recommendation:string;encouragement?:string;amount?:number};
export type AnalysisInput={revenue:number;budgetRevenue?:number|null;expenses:number;budgetExpenses?:number|null;receivables:number;overdueReceivables:number;cashAvailable:number;expectedReceipts30d:number;obligations30d:number;unbilledCompletedServices?:number};
const pct=(v:number)=>`${Math.round(v*100)} %`;
export function analyze(input:AnalysisInput):AnalysisAlert[]{
  const alerts:AnalysisAlert[]=[];const overdueRatio=input.receivables>0?input.overdueReceivables/input.receivables:0;
  if(overdueRatio>.5)alerts.push({code:"receivables",health:"critical",title:"Créances échues critiques",observation:`${pct(overdueRatio)} des créances clients sont échues.`,economicInterpretation:"La qualité du cycle d'exploitation se dégrade : une part importante du chiffre d'affaires reste immobilisée en créances au lieu de se transformer en liquidités.",simpleExplanation:"L'entreprise a vendu, mais une trop grande partie de l'argent reste encore chez les clients.",risk:"La trésorerie peut devenir insuffisante même si l'activité commerciale reste correcte.",recommendation:"Prioriser les factures échues les plus importantes, obtenir des dates fermes de règlement et suivre quotidiennement les promesses de paiement.",amount:input.overdueReceivables});
  else if(overdueRatio>.3)alerts.push({code:"receivables",health:"attention",title:"Créances à traiter",observation:`${pct(overdueRatio)} des créances sont échues.`,economicInterpretation:"Le délai de conversion des ventes en encaissements s'allonge et augmente le besoin de financement d'exploitation.",simpleExplanation:"Les ventes mettent trop de temps à devenir de l'argent disponible.",risk:"Les retards peuvent peser progressivement sur les paiements fournisseurs, fiscaux ou salariaux.",recommendation:"Relancer les clients concernés, documenter les promesses de paiement et cibler d'abord les montants les plus élevés.",amount:input.overdueReceivables});
  else if(overdueRatio>.15)alerts.push({code:"receivables",health:"watch",title:"Créances à surveiller",observation:`${pct(overdueRatio)} des créances sont échues.`,economicInterpretation:"Le portefeuille clients reste globalement maîtrisé, mais les retards commencent à augmenter le besoin en trésorerie.",simpleExplanation:"La situation n'est pas critique, mais certains clients commencent à payer trop tard.",risk:"Une dégradation supplémentaire réduirait la liquidité disponible.",recommendation:"Programmer les relances avant l'accumulation des retards et vérifier les conditions de paiement accordées."});

  const projected30=input.cashAvailable+input.expectedReceipts30d-input.obligations30d;
  if(projected30<0)alerts.push({code:"cash30",health:"critical",title:"Risque de trésorerie à 30 jours",observation:`La projection à 30 jours est déficitaire de ${Math.abs(projected30).toFixed(2)}.`,economicInterpretation:"Les ressources de liquidité attendues sur les trente prochains jours ne couvrent pas les engagements identifiés sur la même période.",simpleExplanation:"Si rien ne change, l'entreprise risque de ne pas avoir assez d'argent pour tout payer dans les 30 prochains jours.",risk:"Certaines échéances pourraient ne pas être couvertes à temps.",recommendation:`Sécuriser au moins ${Math.abs(projected30).toFixed(2)} d'encaissements supplémentaires, différer les sorties non prioritaires et renégocier uniquement les échéances qui peuvent légalement et commercialement l'être.`,amount:Math.abs(projected30)});

  if(input.budgetRevenue&&input.budgetRevenue>0){const variance=(input.revenue-input.budgetRevenue)/input.budgetRevenue;
    if(variance<-.2)alerts.push({code:"revenue_budget",health:"critical",title:"Chiffre d'affaires très inférieur au budget",observation:`Écart de ${pct(variance)} par rapport au budget.`,economicInterpretation:"Le niveau d'activité réalisé est sensiblement inférieur au plan, ce qui réduit la capacité d'absorption des charges fixes et la génération de résultat.",simpleExplanation:"L'entreprise vend nettement moins que prévu alors qu'une partie de ses coûts continue d'exister.",risk:"Le résultat et la capacité de financement peuvent se dégrader rapidement.",recommendation:"Analyser séparément le volume de prospects, le taux de conversion des devis, le prix moyen vendu et les prestations réalisées mais non facturées."});
    else if(variance<-.1)alerts.push({code:"revenue_budget",health:"attention",title:"Chiffre d'affaires sous le budget",observation:`Écart de ${pct(variance)} par rapport au budget.`,economicInterpretation:"L'activité progresse moins vite que prévu et réduit la marge de sécurité disponible pour absorber les charges et financer les investissements.",simpleExplanation:"Les ventes restent en dessous de l'objectif fixé.",risk:"L'objectif de résultat peut devenir difficile à atteindre.",recommendation:"Identifier les segments, services ou clients responsables de l'écart avant d'augmenter les dépenses commerciales."});
    else if(variance>=0&&input.revenue>0)alerts.push({code:"revenue_budget_positive",health:"healthy",title:"Activité conforme ou supérieure au budget",observation:`Le chiffre d'affaires atteint ou dépasse l'objectif de ${pct(variance)}.`,economicInterpretation:"Le niveau d'activité couvre au moins l'objectif commercial prévu pour la période.",simpleExplanation:"Les ventes atteignent l'objectif prévu.",risk:"Une bonne activité ne garantit pas à elle seule une bonne trésorerie ; il faut maintenir la qualité des encaissements et des marges.",recommendation:"Maintenir la dynamique commerciale tout en surveillant la marge et les délais d'encaissement.",encouragement:"La trajectoire commerciale est favorable sur la période observée."});
  }

  if(input.budgetExpenses&&input.budgetExpenses>0){const variance=(input.expenses-input.budgetExpenses)/input.budgetExpenses;
    if(variance>.2)alerts.push({code:"expenses_budget",health:"critical",title:"Charges très supérieures au budget",observation:`Dépassement de ${pct(variance)}.`,economicInterpretation:"Les coûts progressent nettement au-delà du niveau planifié, ce qui comprime la marge et peut dégrader le résultat même si les ventes progressent.",simpleExplanation:"Les dépenses augmentent beaucoup plus que prévu.",risk:"La marge peut se dégrader rapidement.",recommendation:"Identifier les catégories responsables du dépassement et vérifier si elles génèrent effectivement de la valeur ou soutiennent des projets rentables."});
    else if(variance>.1)alerts.push({code:"expenses_budget",health:"attention",title:"Charges au-dessus du budget",observation:`Dépassement de ${pct(variance)}.`,economicInterpretation:"Les charges dépassent le plan et réduisent la capacité de l'entreprise à convertir son chiffre d'affaires en résultat.",simpleExplanation:"L'entreprise dépense plus que prévu.",risk:"Le résultat peut être inférieur à l'objectif.",recommendation:"Contrôler les postes en dépassement avant tout nouvel engagement non indispensable."});
  }

  if((input.unbilledCompletedServices??0)>0)alerts.push({code:"unbilled",health:"attention",title:"Prestations terminées non facturées",observation:`${input.unbilledCompletedServices!.toFixed(2)} de prestations terminées restent à facturer.`,economicInterpretation:"Une partie de l'activité produite n'est pas encore transformée en créance facturée, ce qui retarde le démarrage du cycle d'encaissement.",simpleExplanation:"Le travail est déjà fait, mais les factures correspondantes ne sont pas encore parties.",risk:"Le retard de facturation repousse mécaniquement l'encaissement.",recommendation:"Émettre les factures correspondantes en priorité et vérifier le processus de clôture des missions.",amount:input.unbilledCompletedServices});

  if(!alerts.length&&(input.revenue>0||input.expenses>0||input.cashAvailable>0))alerts.push({code:"stable",health:"healthy",title:"Aucun signal critique détecté",observation:"Les indicateurs disponibles ne déclenchent actuellement aucun seuil d'alerte majeur.",economicInterpretation:"Les données observées ne montrent pas de déséquilibre important selon les règles configurées, mais cette lecture reste limitée aux informations effectivement enregistrées.",simpleExplanation:"Aucun problème important n'est détecté dans les données disponibles pour le moment.",risk:"Une absence d'alerte ne remplace pas le suivi régulier des marges, encaissements et échéances.",recommendation:"Conserver la discipline de saisie et surveiller les tendances plutôt qu'un seul point dans le temps.",encouragement:"La situation observée est maîtrisée au regard des indicateurs disponibles."});
  return alerts.sort((a,b)=>({critical:4,attention:3,watch:2,healthy:1}[b.health]-({critical:4,attention:3,watch:2,healthy:1}[a.health])));
}
