export const FEATURE_CATALOG=[
  {key:"dashboard",label:"Vue d'ensemble",href:"/dashboard",required:true,group:"Pilotage",description:"Vue synthétique de l'activité, la finance et les priorités."},
  {key:"prospects",label:"Prospects",href:"/prospects",required:false,group:"Ventes",description:"Pipeline commercial avant conversion en client."},
  {key:"clients",label:"Clients",href:"/clients",required:true,group:"Ventes",description:"Fiches clients et historique commercial."},
  {key:"services",label:"Services",href:"/services",required:true,group:"Ventes",description:"Catalogue des prestations vendues."},
  {key:"projects",label:"Projets & missions",href:"/projets",required:false,group:"Ventes",description:"Relie ventes, coûts directs et rentabilité par mission."},
  {key:"quotes",label:"Devis",href:"/devis",required:false,group:"Ventes",description:"Propositions commerciales, versions et acceptation."},
  {key:"orders",label:"Commandes",href:"/commandes",required:false,group:"Ventes",description:"Engagement après acceptation d'un devis."},
  {key:"invoices",label:"Factures",href:"/factures",required:false,group:"Ventes",description:"Facturation directe ou issue d'un devis/commande."},
  {key:"payments",label:"Paiements clients",href:"/paiements",required:false,group:"Ventes",description:"Encaissements et règlement des créances."},
  {key:"suppliers",label:"Fournisseurs",href:"/fournisseurs",required:false,group:"Achats",description:"Fournisseurs, sous-traitants et factures fournisseurs."},
  {key:"expenses",label:"Charges & dépenses",href:"/depenses",required:false,group:"Achats",description:"Coûts d'exploitation et décaissements."},
  {key:"treasury",label:"Trésorerie",href:"/tresorerie",required:false,group:"Finance",description:"Banque, caisse, Mobile Money et transferts."},
  {key:"debts",label:"Dettes & engagements",href:"/dettes",required:false,group:"Finance",description:"Obligations fournisseurs, fiscales, sociales et financières."},
  {key:"partner_accounts",label:"Comptes associés",href:"/comptes-associes",required:false,group:"Finance",description:"Sommes dues à ou par les associés."},
  {key:"loans",label:"Emprunts",href:"/emprunts",required:false,group:"Finance",description:"Capital, intérêts et échéancier des financements."},
  {key:"payroll",label:"Personnel & Paie",href:"/paie",required:false,group:"Personnel",description:"Salariés, bulletins, avances et paiements."},
  {key:"tax_social",label:"Fiscalité & Social",href:"/fiscalite-social",required:false,group:"Personnel",description:"Impôts, IRSA, cotisations sociales et santé au travail."},
  {key:"budget",label:"Budget & Prévisions",href:"/budget",required:false,group:"Pilotage",description:"Budget, réalisé et scénarios."},
  {key:"smart_analysis",label:"Analyse intelligente",href:"/analyse",required:false,group:"Pilotage",description:"Santé économique, risques et recommandations."},
  {key:"accounting",label:"Comptabilité",href:"/comptabilite",required:false,group:"Comptabilité",description:"Journaux, écritures, grand livre et balance."},
  {key:"financial_statements",label:"États financiers",href:"/etats-financiers",required:false,group:"Comptabilité",description:"Bilan, résultat et flux de trésorerie."},
  {key:"reports",label:"Rapports",href:"/rapports",required:false,group:"Pilotage",description:"Rapports filtrables et exports."},
  {key:"document_templates",label:"Modèles de documents",href:"/modeles-documents",required:false,group:"Administration",description:"Charte et modèles de devis/factures."},
  {key:"users",label:"Utilisateurs",href:"/utilisateurs",required:true,group:"Administration",description:"Membres, rôles et accès."},
  {key:"audit",label:"Journal d'activité",href:"/audit",required:true,group:"Administration",description:"Traçabilité des actions sensibles."},
  {key:"settings",label:"Paramètres",href:"/parametres",required:true,group:"Administration",description:"Configuration de l'organisation."}
] as const;
export type FeatureKey=(typeof FEATURE_CATALOG)[number]["key"];
