import Link from "next/link";
import {ArrowRight,BarChart3,FileCheck2,Landmark,LineChart,ShieldCheck,WalletCards} from "lucide-react";
import {BrandMark} from "@/components/brand-mark";
import {LandingLoader} from "@/components/landing-loader";

const flow=[
  {icon:FileCheck2,title:"Ventes structurées",text:"Prospects, clients, services, devis, commandes, factures et paiements restent liés sans ressaisie inutile."},
  {icon:WalletCards,title:"Trésorerie réelle",text:"Banque, caisse et Mobile Money sont suivis séparément, avec des mouvements issus des opérations réelles."},
  {icon:LineChart,title:"Santé économique",text:"MAGNISA transforme vos données en diagnostics, explications simples, risques et actions prioritaires."}
];
export default function Home(){return <div className="landing"><LandingLoader/><header className="publicHeader"><BrandMark/><nav className="publicNav"><a href="#produit">Produit</a><a href="#fonctionnalites">Fonctionnalités</a><a href="#pilotage">Pilotage</a><a href="#securite">Sécurité</a></nav><div className="actions"><Link className="button subtle" href="/login">Connexion</Link><Link className="button primary" href="/signup">Commencer</Link></div></header>
<main>
<section className="heroPublic"><div className="heroCopy"><p className="eyebrow">Pilotage d'entreprise, sans rupture d'information</p><h1>Gérez mieux.<br/><span>Décidez mieux.</span></h1><p className="heroLead">Centralisez votre activité, votre trésorerie, vos ventes et vos décisions financières depuis une seule plateforme.</p><div className="actions heroActions"><Link className="button primary large" href="/signup">Commencer <ArrowRight size={17}/></Link><a className="button subtle large" href="#produit">Découvrir MAGNISA</a></div><div className="heroTrust"><ShieldCheck size={18}/><span>Données séparées par organisation, permissions serveur et journal d'audit.</span></div></div>
<div className="productStage" aria-label="Aperçu de l'interface MAGNISA"><div className="stageTop"><div><span className="stageEyebrow">Vue direction</span><strong>Situation économique</strong></div><span className="healthPill">Sain</span></div><div className="stageMetric"><span>Trésorerie disponible</span><strong>—</strong><small>Les montants apparaissent uniquement avec vos données réelles.</small></div><div className="stageChart"><div className="chartAxis"/><div className="chartLine a"/><div className="chartLine b"/></div><div className="stageBottom"><div><BarChart3 size={17}/><span>Activité</span></div><div><Landmark size={17}/><span>Trésorerie</span></div><div><LineChart size={17}/><span>Analyse</span></div></div></div>
</section>
<section id="produit" className="publicSection"><div className="sectionIntro"><p className="eyebrow">Une chaîne métier cohérente</p><h2>Une opération saisie une fois. L'information circule partout où elle doit aller.</h2><p>MAGNISA relie le commercial, la finance, la comptabilité et l'analyse au lieu de juxtaposer des écrans indépendants.</p></div><div className="featureRail">{flow.map(({icon:Icon,title,text})=><article className="featurePanel" key={title}><span className="featureIcon"><Icon/></span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
<section id="fonctionnalites" className="publicSection splitShowcase"><div><p className="eyebrow">De l'opération à la décision</p><h2>Client → Devis → Commande → Facture → Paiement → Trésorerie → Comptabilité → Analyse</h2><p>Chaque étape conserve les relations d'origine, les statuts, les justificatifs et la traçabilité. Les modules peuvent être activés selon les besoins de chaque entreprise.</p></div><div className="flowRibbon">{["Prospect","Client","Devis","Commande","Facture","Paiement","Trésorerie","Analyse"].map((x,i)=><div key={x}><span>{String(i+1).padStart(2,"0")}</span><strong>{x}</strong></div>)}</div></section>
<section id="pilotage" className="publicSection darkShowcase"><div><p className="eyebrow">MAGNISA Analyse</p><h2>Faire parler les chiffres économiquement, puis les expliquer simplement.</h2><p>Le moteur d'analyse compare les données réelles, identifie les tensions, explique les causes probables et formule des recommandations mesurables quand les données sont suffisantes.</p></div><div className="analysisSample"><div><small>Lecture économique</small><p>La rentabilité peut rester positive alors que la liquidité se dégrade si les créances augmentent plus vite que les encaissements.</p></div><div><small>En clair</small><p>L'entreprise peut gagner de l'argent sur le papier tout en manquant d'argent disponible.</p></div><div><small>Action</small><p>Prioriser le recouvrement des factures échues avant les prochaines sorties critiques.</p></div></div></section>
<section id="securite" className="publicSection securityBand"><ShieldCheck size={28}/><div><h2>Conçu pour devenir un vrai logiciel métier.</h2><p>Architecture multi-entreprise, contrôle d'accès côté serveur, RLS, audit, transactions et base PostgreSQL. Aucun faux indicateur n'est nécessaire pour remplir l'écran.</p></div><Link href="/signup" className="button primary large">Créer mon espace</Link></section>
</main><footer className="publicFooter"><BrandMark compact/><span>Plateforme SaaS de gestion et de pilotage d'entreprise.</span></footer></div>}
